name: MobStacker
main: com.kiwifisher.mobstacker.MobStacker
author: KiwiFisher
authors: [Jikoo]
version: ${project.version}
api-version: "1.16"

commands:
  mobstacker:
    usage: /<command> help
    permission: mobstacker.reload;mobstacker.toggle;mobstacker.clearall;mobstacker.inspect;mobstacker.merge

permissions:
  mobstacker.*:
    default: op
    description: Permission to use all MobStacker features.
    children:
      mobstacker.reload:
        default: op
        description: Permission to use /mobstacker reload
      mobstacker.toggle:
        default: op
        description: Permission to use /mobstacker toggle
      mobstacker.clearall:
        default: op
        description: Permission to use /mobstacker clearall
      mobstacker.inspect:
        default: op
        description: Permission to use /mobstacker inspect
      mobstacker.merge:
        default: op
        description: Permission to use /mobstacker merge
